import { Ionicons } from '@expo/vector-icons'; import { useEffect, useRef, useState } from 'react'; import { Pressable, StyleSheet, View, useWindowDimensions } from 'react-native'; import { Gesture, GestureDetector } from 'react-native-gesture-handler'; import Animated,{interpolate,useAnimatedStyle,useSharedValue,withSpring,withTiming} from 'react-native-reanimated';
import { Chip, IconButton, Money, Rule, StrokedImage, Text, duration, settle, useDesignTokens } from '../../../shared/design-system'; import type { CreatorOpportunityFeedItem, OpportunityPreferenceState } from '../types';
type Props={item:CreatorOpportunityFeedItem;reduceMotion:boolean;onAction:(state:OpportunityPreferenceState)=>void;onDetails:()=>void;compact?:boolean};
/** Swipe intent, surfaced as copy and key emphasis so it reads before release. */
type Intent='idle'|'save'|'pass';
const HINT:Record<Intent,string>={idle:'← PASS · SAVE →',save:'RELEASE TO SAVE',pass:'RELEASE TO PASS'};
const daysLeft=(deadline:string)=>{const value=new Date(deadline).getTime();return Number.isFinite(value)?Math.max(0,Math.ceil((value-Date.now())/86400000)):0;};
export function OpportunityCard({item,reduceMotion,onAction,onDetails,compact}:Props){const {width}=useWindowDimensions();const t=useDesignTokens();const x=useSharedValue(0);const leaving=useSharedValue(false);const committed=useRef(false);const [intent,setIntent]=useState<Intent>('idle');const threshold=Math.min(110,width*.25);
 useEffect(()=>{committed.current=false;leaving.value=false;x.value=0;setIntent('idle')},[item.opportunity_id]);
 const finish=(state:OpportunityPreferenceState)=>{if(leaving.value||committed.current)return;leaving.value=true;committed.current=true;setIntent('idle');if(reduceMotion){onAction(state);return}x.value=withTiming(state==='saved'?width*1.3:-width*1.3,{duration:duration.quick});setTimeout(()=>onAction(state),150)};
 const pan=Gesture.Pan().runOnJS(true).enabled(!compact).activeOffsetX([-12,12]).failOffsetY([-20,20]).onUpdate(e=>{if(leaving.value)return;x.value=e.translationX;const reached=Math.abs(e.translationX)>=threshold*.4;setIntent(!reached?'idle':e.translationX>0?'save':'pass')}).onEnd(e=>{if(e.translationX>threshold)finish('saved');else if(e.translationX<-threshold)finish('dismissed');else{setIntent('idle');x.value=withSpring(0,settle)}});
 const cardStyle=useAnimatedStyle(()=>({transform:reduceMotion?[]:[{translateX:x.value},{rotate:`${interpolate(x.value,[-width,0,width],[-4,0,4])}deg`}]})); const save=useAnimatedStyle(()=>({opacity:interpolate(x.value,[threshold*.4,threshold],[0,1],'clamp')}));const pass=useAnimatedStyle(()=>({opacity:interpolate(x.value,[-threshold,-threshold*.4],[1,0],'clamp')}));
 const stamp=(style:any,placement:any,fill:string,label:string)=>reduceMotion?(intent===(label==='Saved'?'save':'pass')?<View style={[s.stamp,placement,s.flat,{backgroundColor:fill,borderColor:t.colors.stroke}]}><Text variant="h2">{label}</Text></View>:null):<Animated.View style={[s.stamp,placement,{backgroundColor:fill,borderColor:t.colors.stroke},style]}><Text variant="h2">{label}</Text></Animated.View>;
 const card=<Animated.View style={[s.card,{borderColor:t.colors.stroke,backgroundColor:t.colors.surface},compact&&s.compact,cardStyle]}><Pressable onPress={onDetails} accessibilityRole="button" accessibilityLabel={`View ${item.opportunity_title}`}><View style={s.hero}><StrokedImage source={{uri:item.hero_image}} style={s.image} contentFit="cover"/><View style={s.badges}>{item.is_prototype?<Chip kind="disclosure" tone="illustrative" label="ILLUSTRATIVE"/>:null}<Chip kind="disclosure" tone="tiktok" label="TIKTOK"/></View>{!compact?<>{stamp(save,s.saved,t.colors.payout,'Saved')}{stamp(pass,s.passed,t.colors.surface,'Pass')}</>:null}</View><View style={s.body}><Text variant="caption">{item.merchant_name}{item.merchant_location?` · ${item.merchant_location}`:''}</Text><Text variant="h1" numberOfLines={2} style={[s.title,{fontFamily:t.fonts.displayBlack}]}>{item.opportunity_title||item.product_title}</Text><Rule/><View style={s.payout}><View><Text variant="label" color={t.colors.payout}>Prize pot</Text><Money amount={Number(item.pot_value??0)} format="prize" emphasis="hero" style={{color:t.colors.payout}}/></View><View><Text variant="label">Per accepted entry</Text><Money amount={Number(item.accepted_entry_fee)} format="payout" emphasis="strong"/></View></View><View style={s.facts}><Text variant="caption">Closes in {daysLeft(item.deadline)} days</Text><View style={s.qualifying}><Text variant="caption">Qualifying purchase from </Text><Money amount={Number(item.price)} format="prize" emphasis="body" style={s.inlineMoney}/></View></View></View></Pressable>{!compact?<View style={[s.actions,{borderTopColor:t.colors.stroke}]}><IconButton accessibilityLabel="Pass for 30 days" onPress={()=>finish('dismissed')} style={intent==='save'&&s.dimmed}><Ionicons name="close" size={t.icons.md} color={t.colors.ink}/></IconButton><Text variant="label" style={s.hint}>{HINT[intent]}</Text><IconButton accessibilityLabel="Save opportunity" variant="payout" onPress={()=>finish('saved')} style={intent==='pass'&&s.dimmed}><Ionicons name="bookmark-outline" size={t.icons.md} color={t.colors.onPayout}/></IconButton></View>:null}</Animated.View>;
 return compact?card:<GestureDetector gesture={pan}>{card}</GestureDetector>}
const s=StyleSheet.create({card:{borderWidth:2,borderRadius:0,overflow:'hidden'},compact:{marginBottom:12},hero:{height:250,position:'relative'},image:{width:'100%',height:'100%',borderWidth:0,borderBottomWidth:2},badges:{position:'absolute',left:12,right:12,top:12,flexDirection:'row',justifyContent:'space-between'},stamp:{position:'absolute',top:52,borderWidth:3,paddingHorizontal:14,paddingVertical:9,transform:[{rotate:'-7deg'}]},saved:{left:12},passed:{right:12},flat:{transform:[]},body:{padding:16,gap:11},title:{fontSize:31,lineHeight:32,letterSpacing:-.93,textTransform:'uppercase'},payout:{flexDirection:'row',alignItems:'flex-end',gap:18},facts:{flexDirection:'row',justifyContent:'space-between',gap:12},qualifying:{flexDirection:'row',alignItems:'center'},inlineMoney:{fontSize:12,lineHeight:18},actions:{flexDirection:'row',alignItems:'center',padding:12,gap:10,borderTopWidth:2},hint:{flex:1,textAlign:'center'},dimmed:{opacity:.4}});
