import { Ionicons } from '@expo/vector-icons'; import { useEffect, useRef } from 'react'; import { Pressable, StyleSheet, View, useWindowDimensions } from 'react-native'; import { Gesture, GestureDetector } from 'react-native-gesture-handler'; import Animated,{interpolate,useAnimatedStyle,useSharedValue,withSpring,withTiming} from 'react-native-reanimated';
import { Chip, IconButton, Money, Rule, StrokedImage, Text, useDesignTokens } from '../../../shared/design-system'; import type { CreatorOpportunityFeedItem, OpportunityPreferenceState } from '../types';
type Props={item:CreatorOpportunityFeedItem;reduceMotion:boolean;onAction:(state:OpportunityPreferenceState)=>void;onDetails:()=>void;compact?:boolean};
const daysLeft=(deadline:string)=>Math.max(0,Math.ceil((new Date(deadline).getTime()-Date.now())/86400000));
export function OpportunityCard({item,reduceMotion,onAction,onDetails,compact}:Props){const {width}=useWindowDimensions();const t=useDesignTokens();const x=useSharedValue(0);const leaving=useSharedValue(false);const committed=useRef(false);const threshold=Math.min(110,width*.25);
 useEffect(()=>{committed.current=false;leaving.value=false;x.value=0},[item.opportunity_id]);
 const finish=(state:OpportunityPreferenceState)=>{if(leaving.value||committed.current)return;leaving.value=true;committed.current=true;if(reduceMotion){onAction(state);return}x.value=withTiming(state==='saved'?width*1.3:-width*1.3,{duration:170});setTimeout(()=>onAction(state),150)};
 const pan=Gesture.Pan().runOnJS(true).enabled(!compact).activeOffsetX([-12,12]).failOffsetY([-20,20]).onUpdate(e=>{if(!leaving.value)x.value=e.translationX}).onEnd(e=>{if(e.translationX>threshold)finish('saved');else if(e.translationX<-threshold)finish('dismissed');else x.value=withSpring(0,{damping:18,stiffness:200})});
 const cardStyle=useAnimatedStyle(()=>({transform:reduceMotion?[]:[{translateX:x.value},{rotate:`${interpolate(x.value,[-width,0,width],[-4,0,4])}deg`}]})); const save=useAnimatedStyle(()=>({opacity:interpolate(x.value,[threshold*.4,threshold],[0,1],'clamp')}));const pass=useAnimatedStyle(()=>({opacity:interpolate(x.value,[-threshold,-threshold*.4],[1,0],'clamp')}));
 const card=<Animated.View style={[s.card,{borderColor:t.colors.stroke,backgroundColor:t.colors.surface},compact&&s.compact,cardStyle]}><Pressable onPress={onDetails} accessibilityRole="button" accessibilityLabel={`View ${item.opportunity_title}`}><View style={s.hero}><StrokedImage source={{uri:item.hero_image}} style={s.image} contentFit="cover"/><View style={s.badges}>{item.is_prototype?<Chip kind="disclosure" tone="illustrative" label="ILLUSTRATIVE"/>:null}<Chip kind="disclosure" tone="tiktok" label="TIKTOK"/></View>{!compact?<><Animated.View style={[s.stamp,s.saved,{backgroundColor:t.colors.payout,borderColor:t.colors.stroke},save]}><Text variant="h2">Saved</Text></Animated.View><Animated.View style={[s.stamp,s.passed,{backgroundColor:t.colors.surface,borderColor:t.colors.stroke},pass]}><Text variant="h2">Pass</Text></Animated.View></>:null}</View><View style={s.body}><Text variant="caption">{item.merchant_name}{item.merchant_location?` · ${item.merchant_location}`:''}</Text><Text variant="h1" numberOfLines={2}>{item.opportunity_title||item.product_title}</Text><Rule/><View style={s.payout}><View><Text variant="label" color={t.colors.payout}>Prize pot</Text><Money amount={Number(item.pot_value??0)} format="prize" emphasis="hero" style={{color:t.colors.payout}}/></View><View><Text variant="label">Per accepted entry</Text><Money amount={Number(item.accepted_entry_fee)} format="payout" emphasis="strong"/></View></View><View style={s.facts}><Text variant="caption">Closes in {daysLeft(item.deadline)} days</Text><Text variant="caption">Qualifying purchase from <MoneyInline value={item.price}/></Text></View></View></Pressable>{!compact?<View style={s.actions}><IconButton accessibilityLabel="Pass for 30 days" onPress={()=>finish('dismissed')}><Ionicons name="close" size={22} color={t.colors.ink}/></IconButton><Text variant="label" style={s.hint}>← PASS · SAVE →</Text><IconButton accessibilityLabel="Save opportunity" variant="payout" onPress={()=>finish('saved')}><Ionicons name="bookmark-outline" size={22} color={t.colors.onPayout}/></IconButton></View>:null}</Animated.View>;
 return compact?card:<GestureDetector gesture={pan}>{card}</GestureDetector>}
function MoneyInline({value}:{value:number}){const t=useDesignTokens();return <Text variant="caption" color={t.colors.ink}>P{value.toFixed(0)}</Text>}
const s=StyleSheet.create({card:{borderWidth:2,borderRadius:0,overflow:'hidden'},compact:{marginBottom:12},hero:{height:250,position:'relative'},image:{width:'100%',height:'100%',borderWidth:0,borderBottomWidth:2},badges:{position:'absolute',left:12,right:12,top:12,flexDirection:'row',justifyContent:'space-between'},stamp:{position:'absolute',top:52,borderWidth:3,paddingHorizontal:14,paddingVertical:9,transform:[{rotate:'-7deg'}]},saved:{left:12},passed:{right:12},body:{padding:16,gap:11},payout:{flexDirection:'row',alignItems:'flex-end',gap:18},facts:{flexDirection:'row',justifyContent:'space-between',gap:12},actions:{flexDirection:'row',alignItems:'center',padding:12,gap:10,borderTopWidth:2},hint:{flex:1,textAlign:'center'}});
