import { Redirect, useRouter } from 'expo-router'; import React, { useEffect, useState } from 'react'; import { ActivityIndicator, Alert, Pressable, StyleSheet, View } from 'react-native';
import { Button, Control, ErrorNotice, Input, Plate, Progress, StackScreenTemplate, Text } from '../../../shared/design-system'; import { useAuth } from '../../../shared/providers/auth-provider'; import { useShopStore } from '../../../store/shop-store'; import { supabase } from '../../../shared/lib/supabase';
export default function OpenShopScreen(){const router=useRouter();const auth=useAuth();const {malls,loadInitialData}=useShopStore();const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);const [name,setName]=useState('');const [location,setLocation]=useState('');const [description,setDescription]=useState('');const [mallId,setMallId]=useState<number|null>(null);const [delivery,setDelivery]=useState(false);const [collection,setCollection]=useState(true);const [alphaCode,setAlphaCode]=useState('');
 useEffect(()=>{if(!malls.length)loadInitialData()},[malls.length,loadInitialData]);useEffect(()=>{if(mallId==null&&malls[0])setMallId(malls[0].id)},[malls,mallId]);useEffect(()=>{if(auth.isMerchant)auth.switchRole('merchant')},[auth.isMerchant]);
 if(auth.mounting)return null;if(!auth.isSignedIn)return <Redirect href="/auth?returnTo=%2Fopen-shop"/>;if(auth.profileError||!auth.session)return <StackScreenTemplate title="Open a shop" fallbackHref="/(shop)/marketplace"><ErrorNotice title="We could not prepare your Muse account" impact="Your sign-in worked, but Muse could not connect your shop profile. Nothing was created or charged." recovery={auth.profileError??'Try again.'}/><Button onPress={()=>void auth.refreshProfile()}>Try again</Button><Button variant="secondary" onPress={()=>void auth.signOut()}>Sign out</Button></StackScreenTemplate>;if(auth.isMerchant)return <Redirect href="/(merchant)"/>;
 const create=async()=>{if(!name.trim()||!location.trim()||mallId==null)return;setBusy(true);try{await auth.createMerchantShop({shopName:name.trim(),shopLocation:location.trim(),shopDescription:description.trim()||undefined,shopMallId:mallId,enableDelivery:delivery,enableCollection:collection});const profile=await auth.refreshProfile();if(profile?.role!=='MERCHANT')throw new Error('Merchant access is still being prepared.');auth.switchRole('merchant');router.replace('/(merchant)')}catch(e){Alert.alert('Shop could not open',e instanceof Error?e.message:'Try again.')}finally{setBusy(false)}};
 const claim=async()=>{if(!alphaCode.trim())return;setBusy(true);try{const {data,error}=await supabase.functions.invoke('claim-alpha-merchant',{body:{code:alphaCode.trim().toUpperCase()}});if(error||data?.error)throw new Error(data?.error??error?.message);await auth.refreshProfile();auth.switchRole('merchant');router.replace('/(merchant)')}catch(e){Alert.alert('Alpha access unavailable',e instanceof Error?e.message:'Check the code.')}finally{setBusy(false)}};
 const valid0=Boolean(name.trim()&&location.trim()&&mallId!=null);const valid1=delivery||collection;
 return <StackScreenTemplate title="Open a shop" fallbackHref="/(shop)/marketplace"><Progress value={(step+1)/3}/><Text variant="label">Step {step+1} / 3</Text>{step===0?<><Text variant="h1">Your business</Text><Input label="Business name" value={name} onChangeText={setName}/><Input label="Trading location" value={location} onChangeText={setLocation}/><Input label="Short description" value={description} onChangeText={setDescription} multiline/><Text variant="label">Mall</Text>{malls.map(m=><Pressable key={m.id} onPress={()=>setMallId(m.id)} style={s.option}><Control kind="radio" selected={mallId===m.id} onPress={()=>setMallId(m.id)} label={m.name}/><Text variant="bodySm">{m.name}</Text></Pressable>)}</>:step===1?<><Text variant="h1">Fulfilment</Text><View style={s.option}><Control kind="switch" selected={collection} onPress={()=>setCollection(!collection)} label="Collection"/><View><Text variant="h3">Collection</Text><Text variant="caption">Customers collect from your trading location.</Text></View></View><View style={s.option}><Control kind="switch" selected={delivery} onPress={()=>setDelivery(!delivery)} label="Delivery"/><View><Text variant="h3">Delivery</Text><Text variant="caption">Bring orders to the customer.</Text></View></View></>:<><Text variant="h1">Add merchant mode</Text><Plate style={s.confirm}><Text variant="body">Opening a shop adds merchant mode without disturbing your bag, saved briefs, orders, or pending checkout.</Text><Text variant="h3">{name}</Text><Text variant="bodySm">{location}</Text><Text variant="caption">{collection?'Collection':''}{collection&&delivery?' · ':''}{delivery?'Delivery':''}</Text></Plate></>}
 <View style={s.actions}>{step>0?<Button variant="secondary" onPress={()=>setStep(step-1)}>Back</Button>:null}{step<2?<Button disabled={step===0?!valid0:!valid1} disabledReason={step===0&&!valid0?'Complete the business details':step===1&&!valid1?'Choose a fulfilment mode':undefined} onPress={()=>setStep(step+1)} style={s.flex}>Continue</Button>:<Button loading={busy} onPress={create} style={s.flex}>Open shop</Button>}</View>
 {step===0?<Plate style={s.alpha}><Text variant="label">Existing alpha merchant</Text><Input label="Access code" value={alphaCode} onChangeText={setAlphaCode} autoCapitalize="characters"/><Button variant="secondary" disabled={!alphaCode.trim()} loading={busy} onPress={claim}>Enter merchant mode</Button></Plate>:null}</StackScreenTemplate>}
const s=StyleSheet.create({option:{minHeight:52,flexDirection:'row',alignItems:'center',gap:10},actions:{flexDirection:'row',gap:9},flex:{flex:1},confirm:{padding:16,gap:10},alpha:{padding:16,gap:10,marginTop:18}});
