import { useUser } from '../shared/clerk'; import { randomUUID } from 'expo-crypto'; import { Redirect, useRouter } from 'expo-router'; import React, { useEffect, useMemo, useRef, useState } from 'react'; import { Alert, StyleSheet, View } from 'react-native';
import { Button, EligibilityPanel, FulfilmentSelector, Input, MerchantIdentityRow, Money, PinnedActionBar, PriceBreakdown, Rule, StackScreenTemplate, Text, formatMoney, useDesignTokens } from '../shared/design-system';
import { calculateCheckoutTotals, isBotswanaPhone, type FulfilmentType } from '../features/cart/domain/commerce'; import { openStripeCheckout, setupStripePaymentSheet } from '../shared/lib/stripe'; import { useAuth as useMuseAuth } from '../shared/providers/auth-provider'; import { useCartStore } from '../store/cart-store';

export default function CheckoutScreen(){
 const t=useDesignTokens(); const router=useRouter(); const {user,isLoaded,isSignedIn}=useUser(); const {session,mounting}=useMuseAuth();
 const store=useCartStore(); const {items,attribution,activeCheckoutKey,checkoutDraft}=store; const shop=items[0]; const [busy,setBusy]=useState(false); const key=useRef(activeCheckoutKey??randomUUID());
 const method:FulfilmentType=checkoutDraft.fulfilment; const totals=useMemo(()=>calculateCheckoutTotals(items,method,shop?.deliveryFee??0),[items,method,shop?.deliveryFee]);
 useEffect(()=>{if(!activeCheckoutKey)store.setActiveCheckoutKey(key.current)},[activeCheckoutKey,store.setActiveCheckoutKey]);
 if(!isLoaded||(isSignedIn&&mounting)) return null; if(!isSignedIn) return <Redirect href={{pathname:'/auth',params:{returnTo:'/checkout'}}}/>; if(!session)return <Redirect href="/auth?returnTo=%2Fcheckout"/>; if(!shop)return <Redirect href="/bag"/>;
 const belowMinimum=totals.subtotalMinor<Math.round((shop.minimumOrderAmount??0)*100); const reason=belowMinimum?`Minimum order is ${formatMoney(Number(shop.minimumOrderAmount??0))}`:!isBotswanaPhone(checkoutDraft.phone)?'Add an 8-digit Botswana phone number':method==='delivery'&&checkoutDraft.address.trim().length<8?'Add a delivery address':undefined;
 const pay=async()=>{if(reason)return;setBusy(true);try{const response=await setupStripePaymentSheet({action:'create',items:items.map(x=>({productId:x.id,quantity:x.quantity})),attribution,idempotencyKey:key.current,customerEmail:user.primaryEmailAddress?.emailAddress??'',fulfilment:{type:method,phone:checkoutDraft.phone.trim(),address:method==='delivery'?checkoutDraft.address.trim():undefined,notes:checkoutDraft.notes.trim()||undefined}});store.setPaymentFlow({orderId:response.orderId,status:response.paymentStatus==='succeeded'?'succeeded':'requires_payment',reservationExpiresAt:(response as any).reservationExpiresAt});if(response.paymentStatus!=='succeeded'){const presented=await openStripeCheckout();if(!presented){router.push({pathname:'/payment-failure',params:{kind:'cancelled'}});return;}store.setPaymentFlow({orderId:response.orderId,status:'processing',reservationExpiresAt:(response as any).reservationExpiresAt});}router.replace({pathname:'/payment-processing',params:{orderId:String(response.orderId)}});}catch(e){Alert.alert('Payment could not continue',e instanceof Error?e.message:'Try again.');router.push({pathname:'/payment-failure',params:{kind:'setup_failed'}});}finally{setBusy(false)}};
 const breakdown={subtotal:totals.subtotalMinor/100,fulfilmentLabel:method==='delivery'?'Delivery':'Collection',fulfilmentFee:totals.deliveryFeeMinor/100,total:totals.totalMinor/100};
 return <StackScreenTemplate title="Review order" fallbackHref="/bag" step={{current:2,total:2}} footer={<PinnedActionBar><Text variant="caption">Stripe sandbox — no real card is charged and no merchant payout occurs.</Text><View style={s.payRow}><View><Text variant="label">Total</Text><Money amount={breakdown.total} emphasis="hero"/></View><Button variant="commerce" loading={busy} disabled={Boolean(reason)} disabledReason={reason} onPress={pay} style={s.pay}>Pay now</Button></View></PinnedActionBar>}>
  <MerchantIdentityRow merchant={{id:shop.shopId,name:shop.shopName}}/><Rule quiet/>
  <View style={s.section}><Text variant="label">Fulfilment</Text><FulfilmentSelector value={method} collection={shop.hasCollection!==false} delivery={Boolean(shop.hasDelivery)} onChange={fulfilment=>store.updateCheckoutDraft({fulfilment})}/><Input label="Phone" keyboardType="phone-pad" value={checkoutDraft.phone} onChangeText={phone=>store.updateCheckoutDraft({phone})}/>{method==='delivery'?<Input label="Delivery address" value={checkoutDraft.address} onChangeText={address=>store.updateCheckoutDraft({address})}/>:null}<Input label="Notes" placeholder="Notes for the shop (optional)" value={checkoutDraft.notes} onChangeText={notes=>store.updateCheckoutDraft({notes})}/></View>
  <Rule quiet/><View style={s.section}><Text variant="label">Order</Text>{items.map(item=><View key={item.id} style={s.line}><Text variant="bodySm">{item.quantity} × {item.title}</Text><Money amount={item.price*item.quantity}/></View>)}<PriceBreakdown model={breakdown}/></View>
  {attribution?.opportunityId?<EligibilityPanel model={{title:'Your linked creator opportunity',perEntry:0,qualifying:true}}/>:null}
 </StackScreenTemplate>;
}
const s=StyleSheet.create({section:{gap:10},methods:{flexDirection:'row',gap:9},method:{flex:1},line:{flexDirection:'row',justifyContent:'space-between',gap:12},payRow:{flexDirection:'row',alignItems:'center',gap:13},pay:{flex:1}});
