import React from 'react'; import { StyleSheet, View } from 'react-native'; import QRCode from 'react-native-qrcode-svg';
import { useDesignTokens } from '../theme/DesignTokensProvider'; import { Text } from '../primitives/Text'; import { Money } from '../primitives/Money'; import { Plate, Rule, StrokedImage } from '../primitives/structure'; import { MerchantMark } from '../primitives/IdentityMark'; import { Button } from '../primitives/Button'; import { Chip } from '../primitives/Chip'; import type { CollectionCodeModel, EligibilityModel, MerchantIdentityModel, OrderTimelineModel, PayoutModel, PriceBreakdownModel } from '../models';
export function MerchantIdentityRow({ merchant, trailing }: { merchant: MerchantIdentityModel; trailing?: React.ReactNode }) { return <View style={s.row}>{merchant.imageUrl?<StrokedImage source={{uri:merchant.imageUrl}} style={s.mark} contentFit="cover"/>:<MerchantMark id={merchant.id} name={merchant.name}/>}<View style={s.flex}><Text variant="h3">{merchant.name}</Text>{merchant.location?<Text variant="caption">{merchant.location}</Text>:null}</View>{trailing}</View>; }
export function PayoutSummary({ payout, inverse=false }: {payout:PayoutModel;inverse?:boolean}) { const t=useDesignTokens(); const color=inverse?t.colors.onInk:t.colors.ink; return <View style={s.payout}>{payout.mode==='competition'?<View><Text variant="label" color={t.colors.payout}>Prize pot</Text><Money amount={payout.pot} format="prize" emphasis="hero" style={{color:t.colors.payout}} /></View>:null}<View><Text variant="label" color={inverse?t.colors.inkMuted:t.colors.inkMuted}>Per accepted entry</Text><Money amount={payout.perEntry} format="payout" emphasis="strong" style={{color}} /></View></View>; }
/** The one coloured plane on a product screen: light fills, dark outlines with a payout edge rule. */
export function EligibilityPanel({ model }: {model:EligibilityModel}) { const t=useDesignTokens(); const pot=Number(model.pot??0); const perEntry=Number(model.perEntry??0); return <View style={[s.eligibility,{backgroundColor:t.mode==='dark'?t.colors.surface:t.colors.payoutSoft,borderLeftColor:t.colors.payout}]}><Text variant="label">Purchase eligibility</Text><Text variant="h3">{model.title}</Text>{pot||perEntry?<View style={s.payout}>{pot?<View><Text variant="label">Prize pot</Text><Money amount={pot} format="prize" emphasis="strong"/></View>:null}{perEntry?<View><Text variant="label">Per accepted entry</Text><Money amount={perEntry} format="payout" emphasis="strong"/></View>:null}</View>:null}<Text variant="bodySm">Buying qualifies you to enter. It does not guarantee acceptance or payment.</Text>{model.illustrative?<Chip kind="disclosure" tone="illustrative" label="ILLUSTRATIVE"/>:null}</View>; }
export function PriceBreakdown({ model, totalHero=false }: {model:PriceBreakdownModel;totalHero?:boolean}) { return <View style={s.stack}><View style={s.between}><Text variant="bodySm">Subtotal</Text><Money amount={model.subtotal}/></View><View style={s.between}><Text variant="bodySm">{model.fulfilmentLabel}</Text><Money amount={model.fulfilmentFee}/></View><Rule quiet/><View style={s.between}><Text variant="h3">Total</Text><Money amount={model.total} emphasis={totalHero?'hero':'strong'}/></View></View>; }
export function OrderStatusStep({ label, detail, state, last=false }: OrderTimelineModel[number]&{last?:boolean}) { const t=useDesignTokens(); return <View style={s.step}><View style={s.track}><View style={[s.dot,{borderColor:state==='pending'?t.colors.strokeDim:t.colors.stroke,backgroundColor:state==='complete'?t.colors.success:state==='current'?t.colors.payout:t.colors.surface}]}/>{!last?<View style={[s.line,{backgroundColor:state==='complete'?t.colors.stroke:t.colors.strokeQuiet}]}/>:null}</View><View style={s.stepCopy}><Text variant="bodySm" color={state==='pending'?t.colors.inkMuted:t.colors.ink}>{label}</Text><Text variant="caption">{detail}</Text></View></View>; }
export function CollectionCode({ model }: {model:CollectionCodeModel}) { const t=useDesignTokens(); return <View style={s.collection}><Text variant="h2" align="center">Show this at the counter</Text><View style={[s.qr,{borderColor:t.colors.stroke}]}><QRCode value={JSON.stringify({orderId:model.orderId,token:model.token})} size={184} backgroundColor="#F5F2EA" color="#101010"/></View><Text variant="h2" selectableData style={{fontFamily:t.fonts.displayBlack,letterSpacing:2.6}}>{model.spokenCode}</Text><Text variant="bodySm" align="center">Or read the code aloud.</Text><Plate style={s.collectPlate}><Text variant="label">Collect from</Text><Text variant="bodySm">{model.merchant}{model.location?`, ${model.location}`:''}</Text></Plate></View>; }
export function EmptyState({title,rule,actionLabel,onAction}: {title:string;rule:string;actionLabel:string;onAction:()=>void}) { return <View style={s.empty}><Text variant="h1" align="center">{title}</Text><Text variant="body" align="center">{rule}</Text><Button onPress={onAction}>{actionLabel}</Button></View>; }
export function ErrorNotice({title,impact,recovery}: {title:string;impact:string;recovery:string}) { const t=useDesignTokens(); return <View style={[s.notice,{borderColor:t.colors.danger,backgroundColor:t.colors.dangerSoft}]}><Text variant="h2" color={t.colors.dangerText}>{title}</Text><Text variant="bodySm">{impact}</Text><Text variant="bodySm">{recovery}</Text></View>; }
const s=StyleSheet.create({row:{flexDirection:'row',alignItems:'center',gap:11},mark:{width:44,height:44,borderWidth:2,borderRadius:0},flex:{flex:1},payout:{flexDirection:'row',alignItems:'flex-end',gap:18},eligibility:{padding:16,borderLeftWidth:4,gap:7},stack:{gap:8},between:{flexDirection:'row',justifyContent:'space-between',gap:12},step:{flexDirection:'row',gap:11,minHeight:52},track:{alignItems:'center'},dot:{width:20,height:20,borderWidth:2,borderRadius:10},line:{width:2,flex:1},stepCopy:{flex:1,paddingBottom:14},collection:{alignItems:'center',gap:14},
// Hard exception to the theme: the quiet zone stays bone in both themes so scanners keep their contrast.
qr:{backgroundColor:'#F5F2EA',padding:12,borderWidth:3},collectPlate:{alignSelf:'stretch',padding:12,gap:4},empty:{padding:24,gap:16,alignItems:'stretch'},notice:{borderWidth:2,padding:15,gap:9}});
