begin;

-- Muse stores references and verification metadata for external TikTok posts.
-- Creator media remains on TikTok and TikTok credentials are never readable
-- through the Data API.

drop policy if exists "Anyone can view challenge submissions" on storage.objects;
drop policy if exists "Authenticated users can upload challenge submissions" on storage.objects;
update storage.buckets set public = false where id = 'challenge-submissions';

alter table public.challenges
  add column if not exists product_id bigint references public.product(id) on delete cascade,
  add column if not exists reward_value numeric(12,2) not null default 50,
  add column if not exists reward_currency text not null default 'BWP',
  add column if not exists voucher_valid_days integer not null default 30,
  add column if not exists manual_verification_enabled boolean not null default false;

create unique index if not exists challenges_active_product_sponsorship_idx
  on public.challenges(product_id)
  where status = 'active' and product_id is not null;

create table if not exists public.creator_platform_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null default 'tiktok' check (platform = 'tiktok'),
  platform_open_id text not null,
  display_name text,
  avatar_url text,
  profile_deep_link text,
  granted_scopes text[] not null default '{}',
  connection_status text not null default 'connected'
    check (connection_status in ('connected', 'expired', 'revoked')),
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, platform),
  unique (platform, platform_open_id)
);

create table if not exists public.creator_platform_tokens (
  account_id bigint primary key references public.creator_platform_accounts(id) on delete cascade,
  access_token text not null,
  refresh_token text not null,
  access_expires_at timestamptz not null,
  refresh_expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

revoke all on public.creator_platform_tokens from public, anon, authenticated;

create table if not exists public.creator_oauth_states (
  state text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  redirect_uri text not null,
  expires_at timestamptz not null,
  consumed_at timestamptz
);
revoke all on public.creator_oauth_states from public, anon, authenticated;

create table if not exists public.purchase_proofs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  shop_id bigint not null references public.shops(id) on delete cascade,
  product_id bigint not null references public.product(id) on delete cascade,
  source text not null check (source in ('order', 'merchant_code')),
  order_id bigint references public."order"(id) on delete cascade,
  redemption_code text,
  amount numeric(12,2) not null default 0,
  currency text not null default 'BWP',
  expires_at timestamptz,
  claimed_at timestamptz,
  consumed_by_submission_id bigint,
  created_at timestamptz not null default now(),
  unique (order_id, product_id),
  unique (redemption_code)
);

create table if not exists public.merchant_purchase_codes (
  id bigint generated by default as identity primary key,
  shop_id bigint not null references public.shops(id) on delete cascade,
  product_id bigint not null references public.product(id) on delete cascade,
  code text not null unique,
  amount numeric(12,2) not null default 0,
  currency text not null default 'BWP',
  expires_at timestamptz not null,
  claimed_by uuid references auth.users(id),
  claimed_at timestamptz,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.challenge_submissions
  alter column content_url drop not null,
  alter column media_type drop not null,
  add column if not exists purchase_proof_id bigint references public.purchase_proofs(id),
  add column if not exists platform_account_id bigint references public.creator_platform_accounts(id),
  add column if not exists platform text not null default 'tiktok',
  add column if not exists platform_video_id text,
  add column if not exists public_share_url text,
  add column if not exists platform_author_open_id text,
  add column if not exists post_description text,
  add column if not exists post_published_at timestamptz,
  add column if not exists verification_status text not null default 'pending'
    check (verification_status in ('pending', 'api_verified', 'manual_verification_required', 'manually_verified', 'failed')),
  add column if not exists verified_at timestamptz,
  add column if not exists consent_version text,
  add column if not exists consented_at timestamptz,
  add column if not exists rejection_reason text,
  add column if not exists reviewed_by uuid references auth.users(id),
  add column if not exists reviewed_at timestamptz;

alter table public.purchase_proofs
  drop constraint if exists purchase_proofs_consumed_by_submission_id_fkey;
alter table public.purchase_proofs
  add constraint purchase_proofs_consumed_by_submission_id_fkey
  foreign key (consumed_by_submission_id) references public.challenge_submissions(id);

create unique index if not exists challenge_submissions_platform_video_idx
  on public.challenge_submissions(platform, platform_video_id)
  where platform_video_id is not null;
create unique index if not exists challenge_submissions_purchase_proof_idx
  on public.challenge_submissions(purchase_proof_id)
  where purchase_proof_id is not null;

create table if not exists public.reward_vouchers (
  id bigint generated by default as identity primary key,
  submission_id bigint not null unique references public.challenge_submissions(id) on delete cascade,
  shop_id bigint not null references public.shops(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  code text not null unique,
  value numeric(12,2) not null,
  currency text not null default 'BWP',
  expires_at timestamptz not null,
  redeemed_at timestamptz,
  redeemed_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.creator_opportunity_preferences (
  user_id uuid not null references auth.users(id) on delete cascade,
  opportunity_id bigint not null references public.challenges(id) on delete cascade,
  state text not null check (state in ('saved', 'dismissed')),
  dismissed_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, opportunity_id),
  check (
    (state = 'saved' and dismissed_until is null)
    or (state = 'dismissed' and dismissed_until is not null)
  )
);

create index if not exists creator_opportunity_preferences_saved_idx
  on public.creator_opportunity_preferences(user_id, updated_at desc)
  where state = 'saved';
create index if not exists creator_opportunity_preferences_dismissed_idx
  on public.creator_opportunity_preferences(user_id, dismissed_until)
  where state = 'dismissed';

create table if not exists public.creator_opportunity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  opportunity_id bigint not null references public.challenges(id) on delete cascade,
  event_type text not null check (event_type in ('impression', 'detail_open')),
  source text not null check (source in ('discover', 'saved', 'marketplace', 'merchant')),
  created_at timestamptz not null default now()
);

create index if not exists creator_opportunity_events_results_idx
  on public.creator_opportunity_events(opportunity_id, event_type, created_at desc);

alter table public."order"
  add column if not exists discovery_source text
    check (discovery_source in ('discover', 'saved', 'marketplace', 'merchant')),
  add column if not exists opportunity_id bigint references public.challenges(id) on delete set null;

create index if not exists order_opportunity_attribution_idx
  on public."order"(opportunity_id)
  where opportunity_id is not null;

create or replace function public.sync_order_purchase_proofs()
returns trigger language plpgsql security definer set search_path = public, pg_catalog as $$
begin
  if new.stripe_payment_status = 'succeeded'
     and old.stripe_payment_status is distinct from new.stripe_payment_status then
    insert into public.purchase_proofs(user_id, shop_id, product_id, source, order_id, amount, currency)
    select new."user", p.shop_id, oi.product, 'order', new.id,
      coalesce(oi.price, 0) * oi.quantity, 'BWP'
    from public.order_item oi join public.product p on p.id = oi.product
    where oi."order" = new.id
    on conflict (order_id, product_id) do nothing;
  end if;
  return new;
end; $$;

drop trigger if exists trg_sync_order_purchase_proofs on public."order";
create trigger trg_sync_order_purchase_proofs after update of stripe_payment_status on public."order"
for each row execute function public.sync_order_purchase_proofs();

create or replace function public.create_merchant_purchase_code(
  p_product_id bigint, p_amount numeric, p_expires_at timestamptz
) returns public.merchant_purchase_codes
language plpgsql security definer set search_path = public, pg_catalog as $$
declare result public.merchant_purchase_codes; target_shop_id bigint;
begin
  select p.shop_id into target_shop_id from public.product p join public.shops s on s.id=p.shop_id
  where p.id=p_product_id and (s.owner_id=auth.uid() or private.is_admin());
  if target_shop_id is null then raise exception 'Merchant does not own this product'; end if;
  insert into public.merchant_purchase_codes(shop_id,product_id,code,amount,expires_at,created_by)
  values(target_shop_id,p_product_id,upper(substr(md5(random()::text || clock_timestamp()::text),1,10)),greatest(p_amount,0),p_expires_at,auth.uid())
  returning * into result;
  return result;
end; $$;

create or replace function public.claim_merchant_purchase_code(p_code text)
returns public.purchase_proofs
language plpgsql security definer set search_path = public, pg_catalog as $$
declare source_code public.merchant_purchase_codes; result public.purchase_proofs;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  select * into source_code from public.merchant_purchase_codes
  where code=upper(trim(p_code)) for update;
  if not found or source_code.expires_at <= now() then raise exception 'Code is invalid or expired'; end if;
  if source_code.claimed_at is not null then raise exception 'Code has already been claimed'; end if;
  update public.merchant_purchase_codes set claimed_by=auth.uid(),claimed_at=now() where id=source_code.id;
  insert into public.purchase_proofs(user_id,shop_id,product_id,source,redemption_code,amount,currency,claimed_at)
  values(auth.uid(),source_code.shop_id,source_code.product_id,'merchant_code',source_code.code,source_code.amount,source_code.currency,now())
  returning * into result;
  return result;
end; $$;

alter table public.creator_platform_accounts enable row level security;
alter table public.creator_platform_tokens enable row level security;
alter table public.creator_oauth_states enable row level security;
alter table public.purchase_proofs enable row level security;
alter table public.merchant_purchase_codes enable row level security;
alter table public.reward_vouchers enable row level security;
alter table public.creator_opportunity_preferences enable row level security;
alter table public.creator_opportunity_events enable row level security;

drop policy if exists "Users read own platform accounts" on public.creator_platform_accounts;
create policy "Users read own platform accounts" on public.creator_platform_accounts
  for select to authenticated using (user_id = (select auth.uid()) or private.is_admin());

drop policy if exists "Users read own purchase proofs" on public.purchase_proofs;
create policy "Users read own purchase proofs" on public.purchase_proofs
  for select to authenticated using (
    user_id = (select auth.uid()) or private.is_admin()
    or exists (select 1 from public.shops s where s.id = purchase_proofs.shop_id and s.owner_id = (select auth.uid()))
  );

drop policy if exists "Merchants read own purchase codes" on public.merchant_purchase_codes;
create policy "Merchants read own purchase codes" on public.merchant_purchase_codes
  for select to authenticated using (
    private.is_admin() or exists (
      select 1 from public.shops s where s.id = merchant_purchase_codes.shop_id and s.owner_id = (select auth.uid())
    )
  );

drop policy if exists "Users and merchants read vouchers" on public.reward_vouchers;
create policy "Users and merchants read vouchers" on public.reward_vouchers
  for select to authenticated using (
    user_id = (select auth.uid()) or private.is_admin()
    or exists (select 1 from public.shops s where s.id = reward_vouchers.shop_id and s.owner_id = (select auth.uid()))
  );

drop policy if exists "Users read own opportunity preferences" on public.creator_opportunity_preferences;
create policy "Users read own opportunity preferences" on public.creator_opportunity_preferences
  for select to authenticated
  using (user_id = (select auth.uid()));

-- Preference and event writes go through checked RPCs. Event rows are aggregate
-- measurement data and are not exposed to customers or merchants.

drop policy if exists "Users can insert their own submissions" on public.challenge_submissions;
drop policy if exists "Users can view approved or own submissions" on public.challenge_submissions;
drop policy if exists "Users can update their own pending submissions" on public.challenge_submissions;
drop policy if exists "Merchants can read campaign submissions" on public.challenge_submissions;
drop policy if exists "Merchants can review campaign submissions" on public.challenge_submissions;

create policy "Users admins and merchants read relevant submissions"
on public.challenge_submissions for select to authenticated using (
  user_id = (select auth.uid()) or private.is_admin()
  or exists (
    select 1 from public.challenges c join public.shops s on s.id = c.shop_id
    where c.id = challenge_submissions.challenge_id and s.owner_id = (select auth.uid())
  )
);

-- Client writes are intentionally denied. Submission, moderation and voucher
-- redemption go through checked SECURITY DEFINER RPCs only.

create or replace function public.submit_creator_opportunity(
  p_challenge_id bigint,
  p_purchase_proof_id bigint,
  p_platform_account_id bigint,
  p_platform_video_id text,
  p_public_share_url text,
  p_platform_author_open_id text,
  p_post_description text,
  p_post_published_at timestamptz,
  p_verification_status text,
  p_consent_version text
) returns public.challenge_submissions
language plpgsql security definer set search_path = public, pg_catalog
as $$
declare result public.challenge_submissions; current_user_id uuid := auth.uid();
begin
  if current_user_id is null then raise exception 'Not authenticated'; end if;
  if p_verification_status not in ('api_verified', 'manual_verification_required') then raise exception 'Invalid verification status'; end if;
  if p_consent_version is null or trim(p_consent_version) = '' then raise exception 'Consent is required'; end if;
  if not exists (
    select 1 from public.purchase_proofs pp join public.challenges c on c.id = p_challenge_id
    where pp.id = p_purchase_proof_id and pp.user_id = current_user_id
      and pp.product_id = c.product_id and pp.shop_id = c.shop_id
      and pp.consumed_by_submission_id is null
      and (pp.expires_at is null or pp.expires_at > now())
  ) then raise exception 'No valid unused purchase proof for this opportunity'; end if;
  if p_platform_account_id is not null and not exists (
    select 1 from public.creator_platform_accounts a
    where a.id = p_platform_account_id and a.user_id = current_user_id
      and a.platform_open_id = p_platform_author_open_id and a.connection_status = 'connected'
  ) then raise exception 'TikTok account ownership could not be verified'; end if;
  if p_verification_status = 'api_verified' and (p_platform_account_id is null or p_platform_video_id is null) then
    raise exception 'API verified submissions require a connected account and video';
  end if;

  insert into public.challenge_submissions (
    challenge_id, user_id, purchase_proof_id, platform_account_id, platform,
    platform_video_id, public_share_url, platform_author_open_id, post_description,
    post_published_at, verification_status, verified_at, consent_version, consented_at,
    status, content_url, media_type
  ) values (
    p_challenge_id, current_user_id, p_purchase_proof_id, p_platform_account_id, 'tiktok',
    nullif(trim(p_platform_video_id), ''), trim(p_public_share_url), nullif(trim(p_platform_author_open_id), ''),
    nullif(trim(p_post_description), ''), p_post_published_at, p_verification_status,
    case when p_verification_status = 'api_verified' then now() else null end,
    p_consent_version, now(), 'pending', null, 'external'
  ) returning * into result;
  return result;
end;
$$;

create or replace function public.review_creator_submission(
  p_submission_id bigint, p_decision text, p_rejection_reason text default null
) returns jsonb
language plpgsql security definer set search_path = public, pg_catalog
as $$
declare s public.challenge_submissions; c public.challenges; voucher public.reward_vouchers;
begin
  if not private.is_admin() then raise exception 'Muse admin access required'; end if;
  if p_decision not in ('approved','rejected') then raise exception 'Invalid decision'; end if;
  select * into s from public.challenge_submissions where id = p_submission_id for update;
  if not found then raise exception 'Submission not found'; end if;
  if s.status <> 'pending' then
    return jsonb_build_object('submission_id', s.id, 'status', s.status, 'idempotent', true);
  end if;
  if p_decision = 'approved' and s.verification_status not in ('api_verified','manually_verified') then
    raise exception 'Submission must be verified before approval';
  end if;
  select * into c from public.challenges where id = s.challenge_id;
  update public.challenge_submissions set status = p_decision,
    rejection_reason = case when p_decision = 'rejected' then nullif(trim(p_rejection_reason),'') else null end,
    reviewed_by = auth.uid(), reviewed_at = now() where id = s.id;
  if p_decision = 'approved' then
    update public.purchase_proofs set consumed_by_submission_id = s.id where id = s.purchase_proof_id and consumed_by_submission_id is null;
    insert into public.reward_vouchers(submission_id, shop_id, user_id, code, value, currency, expires_at)
    values (s.id, c.shop_id, s.user_id, upper(substr(md5(random()::text || clock_timestamp()::text || s.id::text),1,10)),
      c.reward_value, c.reward_currency, now() + make_interval(days => c.voucher_valid_days))
    on conflict (submission_id) do nothing returning * into voucher;
  end if;
  return jsonb_build_object('submission_id', s.id, 'status', p_decision, 'voucher_id', voucher.id, 'idempotent', false);
end;
$$;

create or replace function public.mark_submission_manually_verified(p_submission_id bigint)
returns void language plpgsql security definer set search_path = public, pg_catalog as $$
begin
  if not private.is_admin() then raise exception 'Muse admin access required'; end if;
  update public.challenge_submissions set verification_status = 'manually_verified', verified_at = now()
  where id = p_submission_id and verification_status = 'manual_verification_required';
end; $$;

create or replace function public.redeem_reward_voucher(p_code text)
returns jsonb language plpgsql security definer set search_path = public, pg_catalog as $$
declare v public.reward_vouchers;
begin
  select * into v from public.reward_vouchers where code = upper(trim(p_code)) for update;
  if not found then raise exception 'Voucher not found'; end if;
  if not exists (select 1 from public.shops s where s.id = v.shop_id and (s.owner_id = auth.uid() or private.is_admin())) then
    raise exception 'Voucher belongs to another merchant';
  end if;
  if v.redeemed_at is not null then return jsonb_build_object('voucher_id',v.id,'redeemed',true,'idempotent',true); end if;
  if v.expires_at <= now() then raise exception 'Voucher has expired'; end if;
  update public.reward_vouchers set redeemed_at = now(), redeemed_by = auth.uid() where id = v.id;
  return jsonb_build_object('voucher_id',v.id,'redeemed',true,'idempotent',false);
end; $$;

create or replace function public.get_creator_opportunity_results(p_challenge_id bigint)
returns table(impressions bigint, detail_opens bigint, saves bigint, attributed_purchases bigint,
  eligible_purchasers bigint, connected_creators bigint, submitted_posts bigint,
  verified_posts bigint, approved_posts bigint, vouchers_issued bigint, vouchers_redeemed bigint)
language plpgsql stable security definer set search_path = public, pg_catalog as $$
begin
  if auth.uid() is null or not (
    private.is_admin() or exists (
      select 1 from public.challenges c join public.shops s on s.id=c.shop_id
      where c.id=p_challenge_id and s.owner_id=auth.uid()
    )
  ) then raise exception 'Merchant or Muse admin access required'; end if;
  return query select
    (select count(*) from public.creator_opportunity_events e where e.opportunity_id=p_challenge_id and e.event_type='impression'),
    (select count(*) from public.creator_opportunity_events e where e.opportunity_id=p_challenge_id and e.event_type='detail_open'),
    (select count(*) from public.creator_opportunity_preferences pref where pref.opportunity_id=p_challenge_id and pref.state='saved'),
    (select count(*) from public."order" o where o.opportunity_id=p_challenge_id and o.stripe_payment_status='succeeded'),
    (select count(*) from public.purchase_proofs pp join public.challenges c on c.id=p_challenge_id where pp.product_id=c.product_id and pp.shop_id=c.shop_id),
    count(distinct cs.platform_account_id) filter (where cs.platform_account_id is not null),
    count(cs.id), count(cs.id) filter (where cs.verification_status in ('api_verified','manually_verified')),
    count(cs.id) filter (where cs.status='approved'), count(rv.id), count(rv.id) filter (where rv.redeemed_at is not null)
  from public.challenge_submissions cs left join public.reward_vouchers rv on rv.submission_id=cs.id
  where cs.challenge_id=p_challenge_id;
end;
$$;

create or replace function public.set_creator_opportunity_preference(
  p_opportunity_id bigint,
  p_state text
) returns public.creator_opportunity_preferences
language plpgsql security definer set search_path = public, pg_catalog as $$
declare result public.creator_opportunity_preferences; current_user_id uuid := auth.uid();
begin
  if current_user_id is null then raise exception 'Not authenticated'; end if;
  if p_state not in ('saved', 'dismissed') then raise exception 'Invalid preference state'; end if;
  if not exists (
    select 1 from public.challenges c join public.product p on p.id=c.product_id
    where c.id=p_opportunity_id and c.status='active' and p.is_available is true and p."maxQuantity" > 0
  ) then raise exception 'Creator opportunity is unavailable'; end if;

  insert into public.creator_opportunity_preferences(user_id, opportunity_id, state, dismissed_until)
  values (
    current_user_id,
    p_opportunity_id,
    p_state,
    case when p_state='dismissed' then now() + interval '30 days' else null end
  )
  on conflict (user_id, opportunity_id) do update set
    state=excluded.state,
    dismissed_until=excluded.dismissed_until,
    updated_at=now()
  returning * into result;
  return result;
end; $$;

create or replace function public.restore_creator_opportunity_preference(p_opportunity_id bigint)
returns void language plpgsql security definer set search_path = public, pg_catalog as $$
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  delete from public.creator_opportunity_preferences
  where user_id=auth.uid() and opportunity_id=p_opportunity_id;
end;
$$;

create or replace function public.merge_creator_opportunity_preferences(p_preferences jsonb)
returns integer language plpgsql security definer set search_path = public, pg_catalog as $$
declare item jsonb; merged_count integer := 0; current_user_id uuid := auth.uid(); item_time timestamptz;
begin
  if current_user_id is null then raise exception 'Not authenticated'; end if;
  if jsonb_typeof(p_preferences) <> 'array' or jsonb_array_length(p_preferences) > 200 then
    raise exception 'Invalid preference payload';
  end if;
  for item in select value from jsonb_array_elements(p_preferences)
  loop
    if item->>'state' not in ('saved','dismissed') then continue; end if;
    if not exists (select 1 from public.challenges where id=(item->>'opportunity_id')::bigint) then continue; end if;
    item_time := least(coalesce((item->>'updated_at')::timestamptz, now()), now());
    insert into public.creator_opportunity_preferences(user_id, opportunity_id, state, dismissed_until, created_at, updated_at)
    values (
      current_user_id,
      (item->>'opportunity_id')::bigint,
      item->>'state',
      case when item->>'state'='dismissed' then item_time + interval '30 days' else null end,
      item_time,
      item_time
    )
    on conflict (user_id, opportunity_id) do update set
      state=excluded.state,
      dismissed_until=excluded.dismissed_until,
      updated_at=excluded.updated_at
    where creator_opportunity_preferences.updated_at < excluded.updated_at;
    merged_count := merged_count + 1;
  end loop;
  return merged_count;
end; $$;

create or replace function public.record_creator_opportunity_event(
  p_opportunity_id bigint,
  p_event_type text,
  p_source text
) returns void language plpgsql security definer set search_path = public, pg_catalog as $$
begin
  if auth.uid() is null then return; end if;
  if p_event_type not in ('impression','detail_open') then raise exception 'Invalid event type'; end if;
  if p_source not in ('discover','saved','marketplace','merchant') then raise exception 'Invalid discovery source'; end if;
  if not exists (select 1 from public.challenges where id=p_opportunity_id) then raise exception 'Opportunity not found'; end if;
  insert into public.creator_opportunity_events(user_id,opportunity_id,event_type,source)
  values(auth.uid(),p_opportunity_id,p_event_type,p_source);
end; $$;

create or replace function public.get_creator_opportunity_feed(
  p_cursor integer default 0,
  p_limit integer default 20,
  p_mall_id bigint default null,
  p_seed text default null
) returns table(
  opportunity_id bigint, opportunity_title text, opportunity_description text, requirements text[], deadline text,
  product_id bigint, product_slug text, product_title text, product_description text, hero_image text,
  price double precision, max_quantity bigint, category_id bigint,
  merchant_id bigint, merchant_name text, merchant_location text, mall_id integer,
  has_delivery boolean, has_collection boolean,
  reward_value numeric, reward_currency text, preference_state text,
  eligibility_proof_id bigint, eligibility_consumed boolean, rank_score numeric
) language sql stable security invoker set search_path = public, pg_catalog as $$
  with candidates as (
    select
      c.id opportunity_id, c.title opportunity_title, c.description opportunity_description, c.requirements, c.deadline,
      p.id product_id, p.slug product_slug, p.title product_title, p.description product_description,
      p."heroImage" hero_image, p.price, p."maxQuantity" max_quantity, p.category category_id,
      s.id merchant_id, s.name merchant_name, s.location merchant_location, s.mall_id,
      s.has_delivery, s.has_collection, c.reward_value, c.reward_currency,
      pref.state preference_state,
      proof.id eligibility_proof_id, (proof.consumed_by_submission_id is not null) eligibility_consumed,
      (
        case when p_mall_id is not null and s.mall_id=p_mall_id then 100 else 0 end
        + case when exists (
            select 1 from public.purchase_proofs history
            join public.product hp on hp.id=history.product_id
            where history.user_id=(select auth.uid()) and hp.category=p.category
          ) then 40 else 0 end
        + least(30, greatest(0, coalesce(c.reward_value,0) / greatest(p.price,1) * 30))
        + greatest(0, 20 - extract(epoch from (now()-coalesce(c.created_at,now()))) / 86400)
      )::numeric rank_score,
      md5(c.id::text || coalesce(p_seed,to_char(current_date,'YYYY-MM-DD'))) daily_order
    from public.challenges c
    join public.product p on p.id=c.product_id
    join public.shops s on s.id=c.shop_id and s.id=p.shop_id
    left join public.creator_opportunity_preferences pref
      on pref.opportunity_id=c.id and pref.user_id=(select auth.uid())
    left join lateral (
      select pp.id, pp.consumed_by_submission_id from public.purchase_proofs pp
      where pp.user_id=(select auth.uid()) and pp.product_id=p.id and pp.shop_id=s.id
        and (pp.expires_at is null or pp.expires_at > now())
      order by pp.created_at desc limit 1
    ) proof on true
    where c.status='active' and p.is_available is true and p."maxQuantity" > 0 and s.is_active is true
      and (p_mall_id is null or s.mall_id=p_mall_id)
      and coalesce(pref.state <> 'saved', true)
      and not (pref.state='dismissed' and pref.dismissed_until > now())
  )
  select opportunity_id, opportunity_title, opportunity_description, requirements, deadline,
    product_id, product_slug, product_title, product_description, hero_image,
    price, max_quantity, category_id, merchant_id, merchant_name, merchant_location, mall_id,
    has_delivery, has_collection, reward_value, reward_currency, preference_state,
    eligibility_proof_id, eligibility_consumed, rank_score
  from candidates order by rank_score desc, daily_order
  offset greatest(0,p_cursor) limit least(50,greatest(1,p_limit));
$$;

create or replace function public.get_saved_creator_opportunities()
returns table(
  opportunity_id bigint, opportunity_title text, opportunity_description text, requirements text[], deadline text,
  product_id bigint, product_slug text, product_title text, product_description text, hero_image text,
  price double precision, max_quantity bigint, category_id bigint,
  merchant_id bigint, merchant_name text, merchant_location text, mall_id integer,
  has_delivery boolean, has_collection boolean,
  reward_value numeric, reward_currency text, preference_state text,
  eligibility_proof_id bigint, eligibility_consumed boolean, rank_score numeric
) language sql stable security invoker set search_path = public, pg_catalog as $$
  select
    c.id, c.title, c.description, c.requirements, c.deadline,
    p.id, p.slug, p.title, p.description, p."heroImage", p.price, p."maxQuantity", p.category,
    s.id, s.name, s.location, s.mall_id, s.has_delivery, s.has_collection,
    c.reward_value, c.reward_currency, pref.state,
    proof.id, (proof.consumed_by_submission_id is not null), 0::numeric
  from public.creator_opportunity_preferences pref
  join public.challenges c on c.id=pref.opportunity_id
  join public.product p on p.id=c.product_id
  join public.shops s on s.id=c.shop_id and s.id=p.shop_id
  left join lateral (
    select pp.id, pp.consumed_by_submission_id from public.purchase_proofs pp
    where pp.user_id=(select auth.uid()) and pp.product_id=p.id and pp.shop_id=s.id
      and (pp.expires_at is null or pp.expires_at > now())
    order by pp.created_at desc limit 1
  ) proof on true
  where pref.user_id=(select auth.uid()) and pref.state='saved'
  order by pref.updated_at desc;
$$;

revoke all on function public.submit_creator_opportunity(bigint,bigint,bigint,text,text,text,text,timestamptz,text,text) from public;
grant execute on function public.submit_creator_opportunity(bigint,bigint,bigint,text,text,text,text,timestamptz,text,text) to authenticated;
revoke all on function public.review_creator_submission(bigint,text,text) from public;
grant execute on function public.review_creator_submission(bigint,text,text) to authenticated;
revoke all on function public.mark_submission_manually_verified(bigint) from public;
grant execute on function public.mark_submission_manually_verified(bigint) to authenticated;
revoke all on function public.redeem_reward_voucher(text) from public;
grant execute on function public.redeem_reward_voucher(text) to authenticated;
revoke all on function public.get_creator_opportunity_results(bigint) from public;
grant execute on function public.get_creator_opportunity_results(bigint) to authenticated;
revoke all on function public.set_creator_opportunity_preference(bigint,text) from public;
grant execute on function public.set_creator_opportunity_preference(bigint,text) to authenticated;
revoke all on function public.restore_creator_opportunity_preference(bigint) from public;
grant execute on function public.restore_creator_opportunity_preference(bigint) to authenticated;
revoke all on function public.merge_creator_opportunity_preferences(jsonb) from public;
grant execute on function public.merge_creator_opportunity_preferences(jsonb) to authenticated;
revoke all on function public.record_creator_opportunity_event(bigint,text,text) from public;
grant execute on function public.record_creator_opportunity_event(bigint,text,text) to authenticated;
grant execute on function public.get_creator_opportunity_feed(integer,integer,bigint,text) to anon, authenticated;
revoke all on function public.get_saved_creator_opportunities() from public;
grant execute on function public.get_saved_creator_opportunities() to authenticated;
revoke all on function public.create_merchant_purchase_code(bigint,numeric,timestamptz) from public;
grant execute on function public.create_merchant_purchase_code(bigint,numeric,timestamptz) to authenticated;
revoke all on function public.claim_merchant_purchase_code(text) from public;
grant execute on function public.claim_merchant_purchase_code(text) to authenticated;

grant select on public.creator_platform_accounts, public.purchase_proofs, public.merchant_purchase_codes,
  public.challenge_submissions, public.reward_vouchers, public.creator_opportunity_preferences to authenticated;

commit;
