CREATE TABLE IF NOT EXISTS public.product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.product(id) ON DELETE CASCADE,
  color_name VARCHAR(50) NOT NULL,
  color_hex VARCHAR(7) NOT NULL,
  image_url TEXT,
  stock_quantity INTEGER DEFAULT 0,
  is_available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_product_variants_available ON public.product_variants(is_available);
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_product_color
ON public.product_variants(product_id, color_name);

ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view product variants" ON public.product_variants;
DROP POLICY IF EXISTS "Authenticated users can insert variants" ON public.product_variants;
DROP POLICY IF EXISTS "Authenticated users can update variants" ON public.product_variants;
DROP POLICY IF EXISTS "Authenticated users can delete variants" ON public.product_variants;

CREATE POLICY "Anyone can view product variants"
ON public.product_variants FOR SELECT
USING (true);

CREATE POLICY "Authenticated users can insert variants"
ON public.product_variants FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Authenticated users can update variants"
ON public.product_variants FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can delete variants"
ON public.product_variants FOR DELETE
TO authenticated
USING (true);
