-- Add shop_id to events table
ALTER TABLE public.events
ADD COLUMN IF NOT EXISTS shop_id BIGINT REFERENCES public.shops(id);

CREATE INDEX IF NOT EXISTS idx_events_shop_id ON public.events(shop_id);

CREATE TABLE IF NOT EXISTS public.challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  brand_name TEXT NOT NULL,
  brand_logo_url TEXT,
  reward TEXT NOT NULL,
  deadline TEXT NOT NULL,
  participants_count BIGINT DEFAULT 0,
  image_url TEXT NOT NULL,
  requirements TEXT[] NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  type TEXT NOT NULL DEFAULT 'free',
  ai_allowed BOOLEAN DEFAULT false,
  is_premium BOOLEAN DEFAULT false,
  entry_fee BIGINT,
  category TEXT,
  shop_id BIGINT REFERENCES public.shops(id)
);

-- Add shop_id to challenges table
ALTER TABLE public.challenges
ADD COLUMN IF NOT EXISTS shop_id BIGINT REFERENCES public.shops(id);

CREATE INDEX IF NOT EXISTS idx_challenges_shop_id ON public.challenges(shop_id);
